### ISSUE TITLE
3 questions or suggestions

### ISSUE THREAD

**Issue by PolarisRisingWar** [malllabiisc/CompGCN#16]
1. run.py: error: unrecognized arguments: -init_embed 200
After using "python run.py -score_func transe -opn sub -gamma 9 -hid_drop 0.1 -init_embed 200  " this sentence in terminal, I find that it occurred an error for me said "python run.py -score_func transe -opn sub -gamma 9 -hid_drop 0.1 -init_embed 200  ".
I find that in "run.py" there isn't any "init_embed" code. Is that in fact a "-embed_dim" attribute or other attribute?
2. I'm on Windows, so I have to change "'%H:%M:%S'" to "'%H_%M_%S' or so on. Coz Windows can't support ":" in the name of files.
3. Honestly it's the first time for me to run a deep learning model... And it said my virtual memory is not enough(OSError: [WinError 1455]). I don't know how to deal with it. Maybe I have to buy a new computer?
So I wonder how much memory do I finally need?

**Comment by svjan5** [comment]
Hi @PolarisRisingWar,
1. Thanks for pointing out the issue. It should have been `init_dim` instead of `init_embed`. I have made the correction in the Readme.
2. We have tested the code only on Linux so not sure about its compatibility with windows. If it doesn't work then I would recommend using Linux OS only (dual boot / virtualbox).
3. Yes, the code involves running CompGCN operation on the entire input knowledge graph so it might require some memory. But it works on an 11gb GPU. We used [this](https://www.nvidia.com/en-sg/geforce/products/10series/geforce-gtx-1080-ti/) for getting all our results.
