### ISSUE TITLE
Why do you use outgoing edges as neighbor? 

### ISSUE THREAD

**Issue by renli1024** [malllabiisc/CompGCN#19]
Hi, thanks for opening such a good job first!

I want to know why do you use outgoing edges as node neighbors, instead of ingoing edges, to represent central node. And in this situation TransE model will be formulated as `tail=head-relation`, which I think a little not intuitive? 

Thank you very much.

**Comment by svjan5** [comment]
Hi @renli1024,
One could take only outgoing edges or only incoming edges as the neighbors both will give the same result as we add inverse edges. In our implementation, we went with the outgoing ones. Yes, the TransE model's equations might change a bit if you take the opposite but the overall performance will remain the same as the model can learn `-x` instead of `x`.
