### ISSUE TITLE
What are the best superparameters for WN18RR?

### ISSUE THREAD

**Issue by diligentlee** [malllabiisc/CompGCN#24]
Hello, I want to quote your article, which needs to be reproduced now. Please tell me about the best superparameters of WN18RR, thank you very much.

**Comment by diligentlee** [comment]
python run.py -score_func transe -opn sub -gamma 9 -hid_drop 0.1 -init_dim 200
or
python run.py -score_func transe -opn mult -gamma 9 -hid_drop 0.1 -init_dim 200
didn't work very well on WN18RR

**Comment by junkangwu** [comment]
@svjan5 @soumyasanyal  I ask you about the best hyper parameters for WN18RR? Thanks a lot!

**Comment by soumyasanyal** [comment]
Hi @diligentlee @Wjk666 

Thanks for your interest in the project!

For WN18RR, I think we played around with the dropouts a bit. Can you try this configuration once (with rest parameters set to default)?
model:"compgcn_conve", opn:"mult", gcn_drop:0.2, feat_drop:0.1, hid_drop2:0.4, bias:true, batch_size:256, num_filt:250

If I remember correctly, the default number of filters (200) should be fine as well. Also, please note that convergence might take time (~300 epochs). Let us know the performance of these hyperparams.

**Comment by zwangeo** [comment]
Hi, I seem to have the same problem for WN18RR. 

May I ask that **opn**='dot' you mentioned in the above answer means opn='mult'? Since I only find choices for opn in ['sub', 'mult', 'corr'] based on the provided code. Btw, may I ask how about 'corr' for WN18RR? Is it also suitable?

Thank u so much!!!

**Comment by zwangeo** [comment]
@soumyasanyal 
Hi, I seem to have the same problem for WN18RR. I need to cite your paper and reproduce the result.

May I ask that **opn='dot'** you mentioned in the above answer means opn='mult'? Since I only find choices for opn in ['sub', 'mult', 'corr'] based on the provided code. Btw, may I ask how about 'corr' for WN18RR? Is it also suitable?

Thank u so much!!!

**Comment by soumyasanyal** [comment]
Hi @zwangeo Yes, the operation is mult instead of dot. I've updated the above comment. We renamed dot to mult while finalizing the draft, but I guess the parameter names were not updated correctly in the sheets.

We found simple operators like mult performs better for WN18RR over corr.
